# Generated by Django 4.0.4 on 2023-06-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_faculty_alter_course_user'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydiscussion',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseDiscussions', to='main.student'),
        ),
    ]
