# Generated by Django 4.0.4 on 2023-06-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myuser_is_active_myuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facultyKey',
        ),
        migrations.RemoveField(
            model_name='course',
            name='studentKey',
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CourseKey', to=settings.AUTH_USER_MODEL),
        ),
    ]
